version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mywordbox
    restart: always
    environment:
      # Veritabanı adını burada set ediyoruz
      - POSTGRES_DB=mywordbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5443:5443"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Healthcheck'i de yeni veritabanı adıyla güncelledik
      test: ["CMD-SHELL", "pg_isready -d mywordbox -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mywordbox_network

volumes:
  postgres_data:
    driver: local

networks:
  mywordbox_network:
    driver: bridge